cp Analysis1.C ../mc/
cp Analysis1.h ../mc/
cp W_From_jj.h ../mc/
cp psmain.C ../mc/
cp Makefile ../mc/
cp AnalysisBase.h ../mc/
cp GRL.h ../mc/
cp ObjectQualityMaps_run* ../mc/
cp checkOQ.* ../mc/
cp egammaPIDdefs.h ../mc/
cp robustIsEMDefs.* ../mc/

cp Analysis1.C ../periodA/
cp Analysis1.h ../periodA/
cp Makefile ../periodA/
cp W_From_jj.h ../periodA/
cp psmain.C ../periodA/
cp AnalysisBase.h ../periodA/
cp GRL.h ../periodA/
cp ObjectQualityMaps_run* ../periodA/
cp checkOQ.* ../periodA/
cp egammaPIDdefs.h ../periodA/
cp robustIsEMDefs.* ../periodA/

cp Analysis1.C ../periodB/
cp Analysis1.h ../periodB/
cp Makefile ../periodB/
cp W_From_jj.h ../periodB/
cp psmain.C ../periodB/
cp AnalysisBase.h ../periodB/
cp GRL.h ../periodB/
cp ObjectQualityMaps_run* ../periodB/
cp checkOQ.* ../periodB/
cp egammaPIDdefs.h ../periodB/
cp robustIsEMDefs.* ../periodB/


cp Analysis1.C ../periodC/
cp Analysis1.h ../periodC/
cp Makefile ../periodC/
cp W_From_jj.h ../periodC/
cp psmain.C ../periodC/
cp AnalysisBase.h ../periodC/
cp GRL.h ../periodC/
cp ObjectQualityMaps_run* ../periodC/
cp checkOQ.* ../periodC/
cp egammaPIDdefs.h ../periodC/
cp robustIsEMDefs.* ../periodC/

cp Analysis1.C ../periodD/
cp Analysis1.h ../periodD/
cp Makefile ../periodD/
cp W_From_jj.h ../periodD/
cp psmain.C ../periodD/
cp AnalysisBase.h ../periodD/
cp GRL.h ../periodD/
cp ObjectQualityMaps_run* ../periodD/
cp checkOQ.* ../periodD/
cp egammaPIDdefs.h ../periodD/
cp robustIsEMDefs.* ../periodD/

cp Analysis1.C ../periodE/
cp Analysis1.h ../periodE/
cp Makefile ../periodE/
cp W_From_jj.h ../periodE/
cp psmain.C ../periodE/
cp AnalysisBase.h ../periodE/
cp GRL.h ../periodE/
cp ObjectQualityMaps_run* ../periodE/
cp checkOQ.* ../periodE/
cp egammaPIDdefs.h ../periodE/
cp robustIsEMDefs.* ../periodE/

cp Analysis1.C ../periodF/
cp Analysis1.h ../periodF/
cp Makefile ../periodF/
cp W_From_jj.h ../periodF/
cp psmain.C ../periodF/
cp AnalysisBase.h ../periodF/
cp GRL.h ../periodF/
cp ObjectQualityMaps_run* ../periodF/
cp checkOQ.* ../periodF/
cp egammaPIDdefs.h ../periodF/
cp robustIsEMDefs.* ../periodF/

cp Analysis1.C ../periodG/
cp Analysis1.h ../periodG/
cp Makefile ../periodG/
cp W_From_jj.h ../periodG/
cp psmain.C ../periodG/
cp AnalysisBase.h ../periodG/
cp GRL.h ../periodG/
cp ObjectQualityMaps_run* ../periodG/
cp checkOQ.* ../periodG/
cp egammaPIDdefs.h ../periodG/
cp robustIsEMDefs.* ../periodG/

cp Analysis1.C ../periodH/
cp Analysis1.h ../periodH/
cp Makefile ../periodH/
cp W_From_jj.h ../periodH/
cp psmain.C ../periodH/
cp AnalysisBase.h ../periodH/
cp GRL.h ../periodH/
cp ObjectQualityMaps_run* ../periodH/
cp checkOQ.* ../periodH/
cp egammaPIDdefs.h ../periodH/
cp robustIsEMDefs.* ../periodH/

