########################################3
cp Analysis1.C ../qcd/J0_pythia_jetjetmuon/
cp Analysis1.C ../qcd/J1_pythia_jetjetmuon/
cp Analysis1.C ../qcd/J2_pythia_jetjetmuon/
cp Analysis1.C ../qcd/J3_pythia_jetjetmuon/
cp Analysis1.C ../qcd/J4_pythia_jetjetmuon/
cp Analysis1.C ../qcd/J5_pythia_jetjetmuon/
cp Analysis1.C ../qcd/J6_pythia_jetjetmuon/
cp Analysis1.C ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp Analysis1.C ../ttbar/T1_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp Analysis1.C ../singleTop/st_Wt_McAtNlo_Jimmy/
cp Analysis1.C ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp Analysis1.C ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp Analysis1.C ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp Analysis1.C ../dibosons/WW/
cp Analysis1.C ../dibosons/WZ/
cp Analysis1.C ../dibosons/ZZ/
cp Analysis1.C ../brpvSU3/

cp Analysis1.h ../qcd/J0_pythia_jetjetmuon/
cp Analysis1.h ../qcd/J1_pythia_jetjetmuon/
cp Analysis1.h ../qcd/J2_pythia_jetjetmuon/
cp Analysis1.h ../qcd/J3_pythia_jetjetmuon/
cp Analysis1.h ../qcd/J4_pythia_jetjetmuon/
cp Analysis1.h ../qcd/J5_pythia_jetjetmuon/
cp Analysis1.h ../qcd/J6_pythia_jetjetmuon/
cp Analysis1.h ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp Analysis1.h ../ttbar/T1_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp Analysis1.h ../singleTop/st_Wt_McAtNlo_Jimmy/
cp Analysis1.h ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp Analysis1.h ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp Analysis1.h ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp Analysis1.h ../dibosons/WW/
cp Analysis1.h ../dibosons/WZ/
cp Analysis1.h ../dibosons/ZZ/
cp Analysis1.h ../brpvSU3/

cp GRL.C ../qcd/J0_pythia_jetjetmuon/
cp GRL.C ../qcd/J1_pythia_jetjetmuon/
cp GRL.C ../qcd/J2_pythia_jetjetmuon/
cp GRL.C ../qcd/J3_pythia_jetjetmuon/
cp GRL.C ../qcd/J4_pythia_jetjetmuon/
cp GRL.C ../qcd/J5_pythia_jetjetmuon/
cp GRL.C ../qcd/J6_pythia_jetjetmuon/
cp GRL.C ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp GRL.C ../ttbar/T1_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp GRL.C ../singleTop/st_Wt_McAtNlo_Jimmy/
cp GRL.C ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp GRL.C ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp GRL.C ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp GRL.C ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp GRL.C ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp GRL.C ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp GRL.C ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp GRL.C ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp GRL.C ../dibosons/WW/
cp GRL.C ../dibosons/WZ/
cp GRL.C ../dibosons/ZZ/
cp GRL.C ../brpvSU3/

cp GRL.h ../qcd/J0_pythia_jetjetmuon/
cp GRL.h ../qcd/J1_pythia_jetjetmuon/
cp GRL.h ../qcd/J2_pythia_jetjetmuon/
cp GRL.h ../qcd/J3_pythia_jetjetmuon/
cp GRL.h ../qcd/J4_pythia_jetjetmuon/
cp GRL.h ../qcd/J5_pythia_jetjetmuon/
cp GRL.h ../qcd/J6_pythia_jetjetmuon/
cp GRL.h ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp GRL.h ../ttbar/T1_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp GRL.h ../singleTop/st_Wt_McAtNlo_Jimmy/
cp GRL.h ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp GRL.h ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp GRL.h ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp GRL.h ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp GRL.h ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp GRL.h ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp GRL.h ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp GRL.h ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp GRL.h ../dibosons/WW/
cp GRL.h ../dibosons/WZ/
cp GRL.h ../dibosons/ZZ/
cp GRL.h ../brpvSU3/

cp psmain.C ../qcd/J0_pythia_jetjetmuon/
cp psmain.C ../qcd/J1_pythia_jetjetmuon/
cp psmain.C ../qcd/J2_pythia_jetjetmuon/
cp psmain.C ../qcd/J3_pythia_jetjetmuon/
cp psmain.C ../qcd/J4_pythia_jetjetmuon/
cp psmain.C ../qcd/J5_pythia_jetjetmuon/
cp psmain.C ../qcd/J6_pythia_jetjetmuon/
cp psmain.C ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp psmain.C ../ttbar/T1_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp psmain.C ../singleTop/st_Wt_McAtNlo_Jimmy/
cp psmain.C ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp psmain.C ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp psmain.C ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp psmain.C ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp psmain.C ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp psmain.C ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp psmain.C ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp psmain.C ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp psmain.C ../dibosons/WW/
cp psmain.C ../dibosons/WZ/
cp psmain.C ../dibosons/ZZ/
cp psmain.C ../brpvSU3/

cp W_From_jj.h ../qcd/J0_pythia_jetjetmuon/
cp W_From_jj.h ../qcd/J1_pythia_jetjetmuon/
cp W_From_jj.h ../qcd/J2_pythia_jetjetmuon/
cp W_From_jj.h ../qcd/J3_pythia_jetjetmuon/
cp W_From_jj.h ../qcd/J4_pythia_jetjetmuon/
cp W_From_jj.h ../qcd/J5_pythia_jetjetmuon/
cp W_From_jj.h ../qcd/J6_pythia_jetjetmuon/
cp W_From_jj.h ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp W_From_jj.h ../ttbar/T1_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp W_From_jj.h ../singleTop/st_Wt_McAtNlo_Jimmy/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp W_From_jj.h ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp W_From_jj.h ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp W_From_jj.h ../dibosons/WW/
cp W_From_jj.h ../dibosons/WZ/
cp W_From_jj.h ../dibosons/ZZ/
cp W_From_jj.h ../brpvSU3/


cp Makefile ../qcd/J0_pythia_jetjetmuon/
cp Makefile ../qcd/J1_pythia_jetjetmuon/
cp Makefile ../qcd/J2_pythia_jetjetmuon/
cp Makefile ../qcd/J3_pythia_jetjetmuon/
cp Makefile ../qcd/J4_pythia_jetjetmuon/
cp Makefile ../qcd/J5_pythia_jetjetmuon/
cp Makefile ../qcd/J6_pythia_jetjetmuon/
cp Makefile ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp Makefile ../ttbar/T1_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp Makefile ../singleTop/st_Wt_McAtNlo_Jimmy/
cp Makefile ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp Makefile ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp Makefile ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp Makefile ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp Makefile ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp Makefile ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp Makefile ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp Makefile ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp Makefile ../dibosons/WW/
cp Makefile ../dibosons/WZ/
cp Makefile ../dibosons/ZZ/
cp Makefile ../brpvSU3/

cp AnalysisBase.h ../qcd/J0_pythia_jetjetmuon/
cp AnalysisBase.h ../qcd/J1_pythia_jetjetmuon/
cp AnalysisBase.h ../qcd/J2_pythia_jetjetmuon/
cp AnalysisBase.h ../qcd/J3_pythia_jetjetmuon/
cp AnalysisBase.h ../qcd/J4_pythia_jetjetmuon/
cp AnalysisBase.h ../qcd/J5_pythia_jetjetmuon/
cp AnalysisBase.h ../qcd/J6_pythia_jetjetmuon/
cp AnalysisBase.h ../ttbar/TTbar_FullHad_McAtNlo_Jimmy/
cp AnalysisBase.h ../ttbar/T1_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_schan_enu_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_schan_munu_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_schan_taunu_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_tchan_enu_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_tchan_munu_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_tchan_taunu_McAtNlo_Jimmy/
cp AnalysisBase.h ../singleTop/st_Wt_McAtNlo_Jimmy/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWmunuNp0_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWmunuNp1_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWmunuNp2_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWmunuNp3_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWmunuNp4_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWmunuNp5_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWtaunuNp0_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWtaunuNp1_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWtaunuNp2_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWtaunuNp3_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWtaunuNp4_pt20/
cp AnalysisBase.h ../WplusJets/AlpgenJimmyWtaunuNp5_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZmumuNp0_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZmumuNp1_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZmumuNp2_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZmumuNp3_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZmumuNp4_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZmumuNp5_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZtautauNp0_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZtautauNp1_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZtautauNp2_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZtautauNp3_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZtautauNp4_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZtautauNp5_pt20/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZnunuNp0_pt20_filt1jet/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZnunuNp1_pt20_filt1jet/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZnunuNp2_pt20_filt1jet/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZnunuNp3_pt20_filt1jet/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZnunuNp4_pt20_filt1jet/
cp AnalysisBase.h ../ZplusJets/AlpgenJimmyZnunuNp5_pt20_filt1jet/
cp AnalysisBase.h ../dibosons/WW/
cp AnalysisBase.h ../dibosons/WZ/
cp AnalysisBase.h ../dibosons/ZZ/
cp AnalysisBase.h ../brpvSU3/

